#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTHUVIEN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTHUVIEN")]
	public partial class QLTVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkhoa(khoa instance);
    partial void Updatekhoa(khoa instance);
    partial void Deletekhoa(khoa instance);
    partial void Insertdocgia(docgia instance);
    partial void Updatedocgia(docgia instance);
    partial void Deletedocgia(docgia instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertphanloai(phanloai instance);
    partial void Updatephanloai(phanloai instance);
    partial void Deletephanloai(phanloai instance);
    partial void Insertphieumuon(phieumuon instance);
    partial void Updatephieumuon(phieumuon instance);
    partial void Deletephieumuon(phieumuon instance);
    partial void Insertsach(sach instance);
    partial void Updatesach(sach instance);
    partial void Deletesach(sach instance);
    #endregion
		
		public QLTVDataContext() : 
				base(global::QLTHUVIEN.Properties.Settings.Default.QLTHUVIENConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<khoa> khoas
		{
			get
			{
				return this.GetTable<khoa>();
			}
		}
		
		public System.Data.Linq.Table<docgia> docgias
		{
			get
			{
				return this.GetTable<docgia>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<phanloai> phanloais
		{
			get
			{
				return this.GetTable<phanloai>();
			}
		}
		
		public System.Data.Linq.Table<phieumuon> phieumuons
		{
			get
			{
				return this.GetTable<phieumuon>();
			}
		}
		
		public System.Data.Linq.Table<sach> saches
		{
			get
			{
				return this.GetTable<sach>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khoa")]
	public partial class khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makhoa;
		
		private string _tenkhoa;
		
		private string _diachi;
		
		private System.Nullable<int> _sdt;
		
		private EntitySet<docgia> _docgias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhoaChanging(string value);
    partial void OnmakhoaChanged();
    partial void OntenkhoaChanging(string value);
    partial void OntenkhoaChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(System.Nullable<int> value);
    partial void OnsdtChanged();
    #endregion
		
		public khoa()
		{
			this._docgias = new EntitySet<docgia>(new Action<docgia>(this.attach_docgias), new Action<docgia>(this.detach_docgias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhoa", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makhoa
		{
			get
			{
				return this._makhoa;
			}
			set
			{
				if ((this._makhoa != value))
				{
					this.OnmakhoaChanging(value);
					this.SendPropertyChanging();
					this._makhoa = value;
					this.SendPropertyChanged("makhoa");
					this.OnmakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhoa", DbType="NVarChar(50)")]
		public string tenkhoa
		{
			get
			{
				return this._tenkhoa;
			}
			set
			{
				if ((this._tenkhoa != value))
				{
					this.OntenkhoaChanging(value);
					this.SendPropertyChanging();
					this._tenkhoa = value;
					this.SendPropertyChanged("tenkhoa");
					this.OntenkhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int")]
		public System.Nullable<int> sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khoa_docgia", Storage="_docgias", ThisKey="makhoa", OtherKey="makhoa")]
		public EntitySet<docgia> docgias
		{
			get
			{
				return this._docgias;
			}
			set
			{
				this._docgias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_docgias(docgia entity)
		{
			this.SendPropertyChanging();
			entity.khoa = this;
		}
		
		private void detach_docgias(docgia entity)
		{
			this.SendPropertyChanging();
			entity.khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.docgia")]
	public partial class docgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madocgia;
		
		private string _hoten;
		
		private string _ngaysinh;
		
		private string _makhoa;
		
		private string _diachi;
		
		private string _ngaylapthe;
		
		private string _matkhau;
		
		private EntitySet<phieumuon> _phieumuons;
		
		private EntityRef<khoa> _khoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadocgiaChanging(string value);
    partial void OnmadocgiaChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(string value);
    partial void OnngaysinhChanged();
    partial void OnmakhoaChanging(string value);
    partial void OnmakhoaChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnngaylaptheChanging(string value);
    partial void OnngaylaptheChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public docgia()
		{
			this._phieumuons = new EntitySet<phieumuon>(new Action<phieumuon>(this.attach_phieumuons), new Action<phieumuon>(this.detach_phieumuons));
			this._khoa = default(EntityRef<khoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madocgia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madocgia
		{
			get
			{
				return this._madocgia;
			}
			set
			{
				if ((this._madocgia != value))
				{
					this.OnmadocgiaChanging(value);
					this.SendPropertyChanging();
					this._madocgia = value;
					this.SendPropertyChanged("madocgia");
					this.OnmadocgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="NVarChar(50)")]
		public string ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhoa", DbType="NVarChar(50)")]
		public string makhoa
		{
			get
			{
				return this._makhoa;
			}
			set
			{
				if ((this._makhoa != value))
				{
					if (this._khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhoaChanging(value);
					this.SendPropertyChanging();
					this._makhoa = value;
					this.SendPropertyChanged("makhoa");
					this.OnmakhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylapthe", DbType="NVarChar(50)")]
		public string ngaylapthe
		{
			get
			{
				return this._ngaylapthe;
			}
			set
			{
				if ((this._ngaylapthe != value))
				{
					this.OnngaylaptheChanging(value);
					this.SendPropertyChanging();
					this._ngaylapthe = value;
					this.SendPropertyChanged("ngaylapthe");
					this.OnngaylaptheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="docgia_phieumuon", Storage="_phieumuons", ThisKey="madocgia", OtherKey="madocgia")]
		public EntitySet<phieumuon> phieumuons
		{
			get
			{
				return this._phieumuons;
			}
			set
			{
				this._phieumuons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khoa_docgia", Storage="_khoa", ThisKey="makhoa", OtherKey="makhoa", IsForeignKey=true)]
		public khoa khoa
		{
			get
			{
				return this._khoa.Entity;
			}
			set
			{
				khoa previousValue = this._khoa.Entity;
				if (((previousValue != value) 
							|| (this._khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khoa.Entity = null;
						previousValue.docgias.Remove(this);
					}
					this._khoa.Entity = value;
					if ((value != null))
					{
						value.docgias.Add(this);
						this._makhoa = value.makhoa;
					}
					else
					{
						this._makhoa = default(string);
					}
					this.SendPropertyChanged("khoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieumuons(phieumuon entity)
		{
			this.SendPropertyChanging();
			entity.docgia = this;
		}
		
		private void detach_phieumuons(phieumuon entity)
		{
			this.SendPropertyChanging();
			entity.docgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manhanvien;
		
		private string _hoten;
		
		private string _diachi;
		
		private string _tendangnhap;
		
		private string _matkhau;
		
		private string _quyenhan;
		
		private EntitySet<phieumuon> _phieumuons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanhanvienChanging(string value);
    partial void OnmanhanvienChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OntendangnhapChanging(string value);
    partial void OntendangnhapChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnquyenhanChanging(string value);
    partial void OnquyenhanChanged();
    #endregion
		
		public nhanvien()
		{
			this._phieumuons = new EntitySet<phieumuon>(new Action<phieumuon>(this.attach_phieumuons), new Action<phieumuon>(this.detach_phieumuons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendangnhap", DbType="NVarChar(50)")]
		public string tendangnhap
		{
			get
			{
				return this._tendangnhap;
			}
			set
			{
				if ((this._tendangnhap != value))
				{
					this.OntendangnhapChanging(value);
					this.SendPropertyChanging();
					this._tendangnhap = value;
					this.SendPropertyChanged("tendangnhap");
					this.OntendangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyenhan", DbType="NVarChar(50)")]
		public string quyenhan
		{
			get
			{
				return this._quyenhan;
			}
			set
			{
				if ((this._quyenhan != value))
				{
					this.OnquyenhanChanging(value);
					this.SendPropertyChanging();
					this._quyenhan = value;
					this.SendPropertyChanged("quyenhan");
					this.OnquyenhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_phieumuon", Storage="_phieumuons", ThisKey="manhanvien", OtherKey="manhanvien")]
		public EntitySet<phieumuon> phieumuons
		{
			get
			{
				return this._phieumuons;
			}
			set
			{
				this._phieumuons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieumuons(phieumuon entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_phieumuons(phieumuon entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phanloai")]
	public partial class phanloai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maloai;
		
		private string _tenloai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OntenloaiChanging(string value);
    partial void OntenloaiChanged();
    #endregion
		
		public phanloai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloai", DbType="NVarChar(50)")]
		public string tenloai
		{
			get
			{
				return this._tenloai;
			}
			set
			{
				if ((this._tenloai != value))
				{
					this.OntenloaiChanging(value);
					this.SendPropertyChanging();
					this._tenloai = value;
					this.SendPropertyChanged("tenloai");
					this.OntenloaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieumuon")]
	public partial class phieumuon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madocgia;
		
		private string _ngaymuon;
		
		private string _masach;
		
		private string _manhanvien;
		
		private string _soluong;
		
		private string _trangthai;
		
		private string _ngaytra;
		
		private EntityRef<docgia> _docgia;
		
		private EntityRef<nhanvien> _nhanvien;
		
		private EntityRef<sach> _sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadocgiaChanging(string value);
    partial void OnmadocgiaChanged();
    partial void OnngaymuonChanging(string value);
    partial void OnngaymuonChanged();
    partial void OnmasachChanging(string value);
    partial void OnmasachChanged();
    partial void OnmanhanvienChanging(string value);
    partial void OnmanhanvienChanged();
    partial void OnsoluongChanging(string value);
    partial void OnsoluongChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    partial void OnngaytraChanging(string value);
    partial void OnngaytraChanged();
    #endregion
		
		public phieumuon()
		{
			this._docgia = default(EntityRef<docgia>);
			this._nhanvien = default(EntityRef<nhanvien>);
			this._sach = default(EntityRef<sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madocgia", DbType="NVarChar(50)", IsPrimaryKey=true)]
		public string madocgia
		{
			get
			{
				return this._madocgia;
			}
			set
			{
				if ((this._madocgia != value))
				{
					if (this._docgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadocgiaChanging(value);
					this.SendPropertyChanging();
					this._madocgia = value;
					this.SendPropertyChanged("madocgia");
					this.OnmadocgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaymuon", DbType="NVarChar(50)")]
		public string ngaymuon
		{
			get
			{
				return this._ngaymuon;
			}
			set
			{
				if ((this._ngaymuon != value))
				{
					this.OnngaymuonChanging(value);
					this.SendPropertyChanging();
					this._ngaymuon = value;
					this.SendPropertyChanged("ngaymuon");
					this.OnngaymuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masach", DbType="NVarChar(50)", IsPrimaryKey=true)]
		public string masach
		{
			get
			{
				return this._masach;
			}
			set
			{
				if ((this._masach != value))
				{
					if (this._sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmasachChanging(value);
					this.SendPropertyChanging();
					this._masach = value;
					this.SendPropertyChanged("masach");
					this.OnmasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="NVarChar(50)")]
		public string manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="NVarChar(50)")]
		public string soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(50)")]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytra", DbType="NVarChar(50)")]
		public string ngaytra
		{
			get
			{
				return this._ngaytra;
			}
			set
			{
				if ((this._ngaytra != value))
				{
					this.OnngaytraChanging(value);
					this.SendPropertyChanging();
					this._ngaytra = value;
					this.SendPropertyChanged("ngaytra");
					this.OnngaytraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="docgia_phieumuon", Storage="_docgia", ThisKey="madocgia", OtherKey="madocgia", IsForeignKey=true)]
		public docgia docgia
		{
			get
			{
				return this._docgia.Entity;
			}
			set
			{
				docgia previousValue = this._docgia.Entity;
				if (((previousValue != value) 
							|| (this._docgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._docgia.Entity = null;
						previousValue.phieumuons.Remove(this);
					}
					this._docgia.Entity = value;
					if ((value != null))
					{
						value.phieumuons.Add(this);
						this._madocgia = value.madocgia;
					}
					else
					{
						this._madocgia = default(string);
					}
					this.SendPropertyChanged("docgia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_phieumuon", Storage="_nhanvien", ThisKey="manhanvien", OtherKey="manhanvien", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.phieumuons.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.phieumuons.Add(this);
						this._manhanvien = value.manhanvien;
					}
					else
					{
						this._manhanvien = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_phieumuon", Storage="_sach", ThisKey="masach", OtherKey="masach", IsForeignKey=true)]
		public sach sach
		{
			get
			{
				return this._sach.Entity;
			}
			set
			{
				sach previousValue = this._sach.Entity;
				if (((previousValue != value) 
							|| (this._sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sach.Entity = null;
						previousValue.phieumuons.Remove(this);
					}
					this._sach.Entity = value;
					if ((value != null))
					{
						value.phieumuons.Add(this);
						this._masach = value.masach;
					}
					else
					{
						this._masach = default(string);
					}
					this.SendPropertyChanged("sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sach")]
	public partial class sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masach;
		
		private string _nhande;
		
		private System.Nullable<int> _sotrang;
		
		private System.Nullable<int> _soluong;
		
		private string _namxb;
		
		private System.Nullable<int> _lanxb;
		
		private System.Nullable<int> _solanmuon;
		
		private string _maloai;
		
		private string _nxb;
		
		private string _tacgia;
		
		private string _ngaynhap;
		
		private EntitySet<phieumuon> _phieumuons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasachChanging(string value);
    partial void OnmasachChanged();
    partial void OnnhandeChanging(string value);
    partial void OnnhandeChanged();
    partial void OnsotrangChanging(System.Nullable<int> value);
    partial void OnsotrangChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnnamxbChanging(string value);
    partial void OnnamxbChanged();
    partial void OnlanxbChanging(System.Nullable<int> value);
    partial void OnlanxbChanged();
    partial void OnsolanmuonChanging(System.Nullable<int> value);
    partial void OnsolanmuonChanged();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OnnxbChanging(string value);
    partial void OnnxbChanged();
    partial void OntacgiaChanging(string value);
    partial void OntacgiaChanged();
    partial void OnngaynhapChanging(string value);
    partial void OnngaynhapChanged();
    #endregion
		
		public sach()
		{
			this._phieumuons = new EntitySet<phieumuon>(new Action<phieumuon>(this.attach_phieumuons), new Action<phieumuon>(this.detach_phieumuons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masach", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masach
		{
			get
			{
				return this._masach;
			}
			set
			{
				if ((this._masach != value))
				{
					this.OnmasachChanging(value);
					this.SendPropertyChanging();
					this._masach = value;
					this.SendPropertyChanged("masach");
					this.OnmasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhande", DbType="NVarChar(50)")]
		public string nhande
		{
			get
			{
				return this._nhande;
			}
			set
			{
				if ((this._nhande != value))
				{
					this.OnnhandeChanging(value);
					this.SendPropertyChanging();
					this._nhande = value;
					this.SendPropertyChanged("nhande");
					this.OnnhandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotrang", DbType="Int")]
		public System.Nullable<int> sotrang
		{
			get
			{
				return this._sotrang;
			}
			set
			{
				if ((this._sotrang != value))
				{
					this.OnsotrangChanging(value);
					this.SendPropertyChanging();
					this._sotrang = value;
					this.SendPropertyChanged("sotrang");
					this.OnsotrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namxb", DbType="Char(10)")]
		public string namxb
		{
			get
			{
				return this._namxb;
			}
			set
			{
				if ((this._namxb != value))
				{
					this.OnnamxbChanging(value);
					this.SendPropertyChanging();
					this._namxb = value;
					this.SendPropertyChanged("namxb");
					this.OnnamxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxb", DbType="Int")]
		public System.Nullable<int> lanxb
		{
			get
			{
				return this._lanxb;
			}
			set
			{
				if ((this._lanxb != value))
				{
					this.OnlanxbChanging(value);
					this.SendPropertyChanging();
					this._lanxb = value;
					this.SendPropertyChanged("lanxb");
					this.OnlanxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solanmuon", DbType="Int")]
		public System.Nullable<int> solanmuon
		{
			get
			{
				return this._solanmuon;
			}
			set
			{
				if ((this._solanmuon != value))
				{
					this.OnsolanmuonChanging(value);
					this.SendPropertyChanging();
					this._solanmuon = value;
					this.SendPropertyChanged("solanmuon");
					this.OnsolanmuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="NVarChar(50)")]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nxb", DbType="NVarChar(50)")]
		public string nxb
		{
			get
			{
				return this._nxb;
			}
			set
			{
				if ((this._nxb != value))
				{
					this.OnnxbChanging(value);
					this.SendPropertyChanging();
					this._nxb = value;
					this.SendPropertyChanged("nxb");
					this.OnnxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tacgia", DbType="NVarChar(50)")]
		public string tacgia
		{
			get
			{
				return this._tacgia;
			}
			set
			{
				if ((this._tacgia != value))
				{
					this.OntacgiaChanging(value);
					this.SendPropertyChanging();
					this._tacgia = value;
					this.SendPropertyChanged("tacgia");
					this.OntacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="NVarChar(50)")]
		public string ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sach_phieumuon", Storage="_phieumuons", ThisKey="masach", OtherKey="masach")]
		public EntitySet<phieumuon> phieumuons
		{
			get
			{
				return this._phieumuons;
			}
			set
			{
				this._phieumuons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieumuons(phieumuon entity)
		{
			this.SendPropertyChanging();
			entity.sach = this;
		}
		
		private void detach_phieumuons(phieumuon entity)
		{
			this.SendPropertyChanging();
			entity.sach = null;
		}
	}
}
#pragma warning restore 1591
